### ISSUE TITLE
Some packages seem to be considered unfree merely for being multi-licensed

### ISSUE THREAD

**Issue by nemobis** [suve/vrms-rpm#76] opened 2021-01-20 17:04 UTC
The `--explain` option is very useful but I'm not sure I understand this explanation:
```
$ LANG=en_GB vrms-rpm --explain | grep -B1 ", MIT"
 - gobject-introspection
   GPLv2+, LGPLv2+, MIT
--
 - lttng-ust
   LGPLv2.1, MIT and GPLv2
$ vrms-rpm --version
vrms-rpm v.2.2 by suve
```

Why are those MIT etc. licenses listed as red? Is it maybe a parsing failure where the comma separator is not recognised, and the string "LGPLv2.1, MIT" fails to match a license?

**Comment by suve** [comment] 2021-01-20 17:48
Yes, currently the comma is not recognized as a separator. This was an intentional choice, as the tool was developed mainly for use with Fedora, and Fedora's Packaging Guidelines state that only `and` and `or` should be used as separators.
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_dual_licensing_scenarios
https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_multiple_licensing_scenarios

I suppose we could try interpreting the comma as a separator, but that brings about the question - how to interpret it? Interpreting the comma as `or` can create false-negatives, and interpreting it as `and` can create false positives. Arguably, the second option is better, since it fits the "non-free until proven otherwise" approach better.

**Comment by nemobis** [comment] 2021-01-20 20:07
Understood. Should I then report the issue to the package maintainer 
instead? Thank you.

**Comment by christianitis** [comment] 2021-06-14 01:29
This also happens to me. I'm on OpenSUSE Tumbleweed, and it's listing around %50 of my packages as nonfree solely because they have multiple licenses. Considering Fedora is now essentially dead, and many of it's former users are now moving to Suse, shouldn't this be fixed?

**Comment by suve** [comment] 2021-06-14 07:23
> Considering Fedora is now essentially dead

What.

Also, please give an example. If this is caused by packages using
```
LicenceOne, LicenceTwo
```
then check my comment above about handling the comma as a licence separator.

**Comment by christianitis** [comment] 2021-06-14 21:19
> > Considering Fedora is now essentially dead
> 
> What.

Sorry, meant CentOS, not Fedora. Leap has been getting a lot of refugees from CentOS.

**Comment by christianitis** [comment] 2021-06-14 21:28
> Also, please give an example. If this is caused by packages using
>> LicenceOne, LicenceTwo
>
> then check my comment above about handling the comma as a licence separator.

I think I see the problem: it seems that the license detector is case-sensitive, and does not recognize multi-licensed packages which use capital AND/OR as seperators.

`vrms-rpm --explain` returns this:
`vlc
   GPL-2.0-or-later AND LGPL-2.1-or-later
x11-tools
   GPL-2.0-or-later AND MIT
yast2-journal
   GPL-2.0-only OR GPL-3.0-only
`
et cetera et cetera.

Notice how the ANDs and ORs are capitalized. I think that may be the problem.
This should be a simple fix. I'd do it myself if not for my lack of knowledge of the C programming language.

**Comment by suve** [comment] 2021-06-14 21:30
> Sorry, meant CentOS, not Fedora.

Oh yeah, agreed on that. With the announcement of CentOS Stream - which meant that CentOS stopped being "free RHEL without the branding" - a lot of people started migrating. I've heard of Rocky Linux continuing the idea.

Thanks for the examples. Yes, the current code performs a case-sensitive search when looking for `and`/`or` joiners. Making this case-insensitive is a simple change.

**Comment by christianitis** [comment] 2021-06-14 21:31
> > Sorry, meant CentOS, not Fedora.
> 
> Oh yeah, agreed on that. With the announcement of CentOS Stream - which meant that CentOS stopped being "free RHEL without the branding" - a lot of people started migrating. I've heard of Rocky Linux continuing the idea.
> 
> Thanks for the examples. Yes, the current code performs a case-sensitive search when looking for `and`/`or` joiners. Making this case-insensitive is a simple change.

Awesome, glad I could help. And thank you for rewriting this for RPM-based systems!

**Comment by suve** [comment] 2021-07-16 14:12
I pushed some initial support for case-insensitive `and`/`or` joiners to the [`case-insensitive-joiners`](https://github.com/suve/vrms-rpm/compare/trunk...case-insensitive-joiners) branch. While the code seems to work fine, the running time is roughly +33% compared to the old solution, so I want to take a bit more time and think on how to improve that.

**Comment by nmonti** [comment] 2022-01-21 03:39
This issue happened to me with the following libraries. The bolded are red in terminal:

```
 - librados2
   (LGPLv2.1 or LGPLv3) and CC-BY-SA-3.0 and GPLv2 and **Boost-1.0** and BSD and MIT
 - librbd1
   (LGPLv2.1 or LGPLv3) and CC-BY-SA-3.0 and GPLv2 and **Boost-1.0** and BSD and MIT
 - lttng-ust
   **LGPLv2.1, MIT** and GPLv2
```

[Boost](http://directory.fsf.org/wiki/License:Boost1.0) is free, and I'm not sure what caused `LGPLv2.1, MIT` to be flagged.

**Comment by suve** [comment] 2022-01-21 09:58
@nmonti as mentioned earlier, `X, Y` is recognized as a single name, not `(X or Y)` nor `(X and Y)`.

**Comment by suve** [comment] 2023-08-25 10:32
Opened issue #93 for tracking progress on adding support for comma-separated licence expressions. Closing this ticket.

**Closed as not planned by suve** 2023-08-25 10:32 UTC
